version = 0.1
[default.deploy.parameters]
stack_name = "springboot-on-lambda"
resolve_s3 = true
s3_prefix = "springboot-on-lambda"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
