AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  SpringOnLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: com.eudaimonia.swissarmysteel.LambdaHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 2048
      SnapStart:
        ApplyOn: "PublishedVersions"
      AutoPublishAlias: "prod"
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY